### ISSUE TITLE
same product with different links

### ISSUE THREAD

**Issue by kan0ne** [franzholz/tt_products#41]
hello,

i am facing a new issue and idont know how to fix this. hope u can help me

typo3 8.7.18
tt_products 2.9.3

i have a solr search on my site.
And when i search for a word, i get several products on the result page with links to the product (links are correct).
like: 
.../shop/detail/?no_cache=1&tt_products%5Bproduct%5D=677
or
.../shop/detail?no_cache=1&tt_products%5Bproduct%5D=159

no matter what link i press it opens the same product.

After deleting typo3 cache, no matter what product i click it opens the first product, that was loaded after cache deleting.

when i add a chash to to the link it works and the correct product is displayed.
in the installtool pageNotFoundOnCHashError = false

greetings martin

**Comment by franzholz** [comment]
This only happens because "no_cache=1" seems to have no effect any more on TYPO3 8. Otherwise the correct product would have been shown instead of the cached one.
You must provide the cHash Parameter with your links.

Alternative:
Use a USER_INT instead of USER for the tt_products Setup. This can be done by adding the "Shop System Variable Content" at "Include static (from extensions):".

**Comment by kan0ne** [comment]
thx for the help.

the alternative version worked for me!
