### ISSUE TITLE
Image field is not migrated to FAL automatically

### ISSUE THREAD

**Issue by responseinformationsdesign** [franzholz/tt_products#84]
Upload comment for version 2.9.13: 

> Do not remove the tt_products image fields in the Install Tool before you have successfully executed the image FAL migration tool.

How can the "FAL migration tool" be executed?

**Comment by franzholz** [comment]
You must use the TYPO3 Install Tool. There you will see the tt_products migration tools. They will check automatically if a migration is necessary. They are only visible if a migration is necessary.

**Comment by responseinformationsdesign** [comment]
I´m still unable to find the wizard in the TYPO3 install tool (TYPO3 9.5).
The only step in relation to `tt_products` in the upgrade wizard is
`EXT:tt_products - Migrate order to product relations because of new requirements for IRRE inline intermediate tables in TYPO3.`

**Comment by franzholz** [comment]
The TYPO3 upgrade wizards in the Install Tool are only available in TYPO3 10 and later.

In TYPO3 9.5 you must rename the table fields manually by phpMyAdmin as described in the ChangeLog.

**Comment by responseinformationsdesign** [comment]
Sorry, can´t find such a comment in https://github.com/franzholz/tt_products/blob/master/ChangeLog.

**Comment by franzholz** [comment]
I have modified the ChangeLog file now.

Only tt_products 2.13.2 supports FAL also in TYPO3 9.5, because it has an upgrade function in the extension func, the function module. tt_products 2.9.16 has FAL only under TYPO3 10.4. 
All upgrade wizards are in TYPO3 10.4 only.

    tt_products_mm_graduated_price is sometimes missing. product_uid ==> uid_local
    graduated_price_uid ==> uid_foreign

**Comment by responseinformationsdesign** [comment]
By the way - new added images via the FAL field in TYPO3 9.5 / tt_products 2.9.16 work flawlessly.

**Comment by fxp66** [comment]
I have the same issue when I 've updated the whole system to typo3 10.4.15 and tt_products 2.9.16.
The wizzard in installtool shows no option to migrate the images.
Is it correct that this version has only the option to store images with FAL?
How can I migrate the images manually?
![screen-1](https://user-images.githubusercontent.com/40458047/114849775-60f77f80-9de0-11eb-810e-4708938b2624.png)

**Comment by franzholz** [comment]
If no upgrade wizard for the tt_products images is shown in TYPO3 10, then this means, that there are no images.
Maybe you have removed all image fields from the tt_products records? They are still needed for the upgrade wizard.

TYPO3 10 requires all images to be in the FAL format.

**Comment by fxp66** [comment]
Thx for your support, installing the latest vers. 2.9.16 fixed the issue and I migrated all throug Update Wizzard.

**Comment by responseinformationsdesign** [comment]
In the TYPO3 install tool next to all other migration wizards.

**Comment by franzholz** [comment]
But this TYPO3 9.5 FAL migration wizard: Is this a part of TYPO3? Does it support tt_products 2.9.17 FAL migration? How does it know that the image field of tt_products is "image", but the FAL image field is "image_uid"?

	image text,
	image_uid int(11) DEFAULT '0' NOT NULL,
	smallimage text,
	smallimage_uid int(11) DEFAULT '0' NOT NULL,
	datasheet text,
	datasheet_uid int(11) DEFAULT '0' NOT NULL,

**Comment by fxp66** [comment]
I have issues while trying to migrate the images after update from tt_products 9.9.0 up to 9.20 within typo3 10.4.
Migration of the datasheets is working well, but when trying to migrate the images I get the error 'file not exist in user_upload'
althoug they are stored in 'fileadmin/user_upload/catalog/pics' and this path is configured in EM.

Update wizard works without any error for the database update, but the wizard always searchs in 'user_uploads' with no result.
So I've tried to note the correct path in ProductImageUpdater.php and the wizard works without errors.
The images now are shown in listview but single view throws error 'oops .....'.

So I stored the images in 'user_upload' with the origin ProductImageUpdater.php and migration of images works as well
for list and singleview. I can't leave this that way, because it is my productive website and it has to keep the folder structure in fal.

Do you have any further hint to solve this problem? Maybe it is not an error of tt_products, and it occurs when you update typo3 9 up to typo3 10?

thx for your reply fxp

**Comment by franzholz** [comment]
The Upgrade Wizard of product images for the Install Tool has only been implemented for the folder 'uploads/pics'. More work is needed to support a different folder structure.
[uploads/pics in image updater](https://github.com/franzholz/tt_products/blob/0ab47f6b3aa2b1c2ceface461f5b21f122b000af/Classes/Updates/ProductImageUpdater.php#L172)

**Comment by fxp66** [comment]
That's exactly, what I've changed. So would you please give me further advice what to do.

thx fxp

**Comment by franzholz** [comment]
I have made a change now.
Only the 'imageFolder' set in the Extension Manager is needed. Then the images are read from this folder.

**Comment by fxp66** [comment]
Thanks a lot, I'll try this and giv you feedback

thx fxp
